baseURL = 'https://nhasian.github.io/'
languageCode = 'en-us'
title = 'Nassers Blog'
theme = 'PaperMod'
[services]
  [services.googleAnalytics]
    ID = ''
[caches]
  [caches.images]
    dir = ':cacheDir/images'
